server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://default-mysql-service-84b8d-27082928-aeb0167bd00f.kr.lb.naverncp.com:13306/jungmae-chat?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:

          naver:
            client-id: FP0nQnEUGIXGn_Ur7oqm
            client-secret: yJEZHNMrSs
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver   # ???? ??? ???? ??? ??? ?????.

        provider:
          naver:  # ???? provider??? ???? ??? ?? ??? ???? ??.
            authorization-uri: https://nid.naver.com/oauth2.0/authorize   # ??? ???? ??  "/oauth2/authorization/naver" ??? ?? ? uri?  ????.
            token-uri: https://nid.naver.com/oauth2.0/token   # ?? ?? ?? ??
            user-info-uri: https://openapi.naver.com/v1/nid/me    # ?? ??? ??? ??? ?? API ??
            user-name-attribute: response   #  ????? json?? ??? response?? ???? ???? ????.