server:
  port: 0
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: login-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}:3306/jungmae-chat
#    url: jdbc:mysql://${MYSQL_URL}:3306/jungmae-auction
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/oauth2/navercallback   # ???? ??? ???? ??? ??? ?????.

        provider:
          naver:  # ???? provider??? ???? ??? ?? ??? ???? ??.
            authorization-uri: https://nid.naver.com/oauth2.0/authorize   # ??? ???? ??  "/oauth2/authorization/naver" ??? ?? ? uri?  ????.
            token-uri: https://nid.naver.com/oauth2.0/token   # ?? ?? ?? ??
            user-info-uri: https://openapi.naver.com/v1/nid/me    # ?? ??? ??? ??? ?? API ??
            user-name-attribute: response   #  ????? json?? ??? response?? ???? ???? ????.

logging:
  level:
    login.jungmae.login: DEBUG